name = "Trixi2Img"
uuid = "821991e7-028e-4e54-884c-f74f8833bc95"
authors = ["Michael Schlottke-Lakemper <mschlott@math.uni-koeln.de>"]
version = "0.2.3"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
ArgParse = "1.1"
EllipsisNotation = "1"
GR = "0.51, 0.52, 0.53"
Glob = "1.3"
HDF5 = "0.14"
Plots = "1.6"
TimerOutputs = "0.5"
julia = "1.5"
